  - name: Update the agent to the latest version 
    apt: name=rackspace-monitoring-agent state=latest update_cache=yes

  - name: Check /etc/rackspace-monitoring-agent.conf.d/
    file: dest=/etc/rackspace-monitoring-agent.conf.d/ state=directory owner=root group=root

  - name: Check /usr/lib/rackspace-monitoring-agent/plugins
    file: dest=/usr/lib/rackspace-monitoring-agent/plugins state=directory owner=root group=root
