  - name: Download lsyncd-status.sh 
    get_url: 
      url: https://raw.githubusercontent.com/racker/rackspace-monitoring-agent-plugins-contrib/master/lsyncd-status.sh 
      dest: /usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh
      mode: 0744
      owner: root
      group: root
    notify: restart rackspace-monitoring-agent

  - name: Copy lsyncd_check.yaml 
    copy: src=lsyncd_check.yaml dest=/etc/rackspace-monitoring-agent.conf.d/lsyncd_check.yaml
    notify: restart rackspace-monitoring-agent
